name: example
description: Example app on how to use Flutter Nes
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: 3.3.10

dependencies:
  flutter:
    sdk: flutter
  nes:
    path: ../

dev_dependencies:
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
